### ISSUE TITLE
.Net Core 2.0 Compatibility

### ISSUE THREAD

**Issue by barissonmez** [kanisimoff/PluralizeService.Core#1]
I have installed the library into a .net core 2.0 project and VS created a warning message as below:
"Warning	NU1701	Package 'Pluralize.NET 0.1.43' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project."

**Comment by kanisimoff** [comment]
I think you confuse the package "Pluralize.NET 0.1.43" with "PluralizeService.Core" v.1.0.0.5. These are two different products. In general you are right because of the non-compatibility of the native version, I recompiled the .net framework native code underneath the .net core and placed the library "PluralizeService.Core" to not do this in other projects. As I think this library should be claimed.
